# Generated by Django 5.0.6 on 2024-05-29 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
