# Generated by Django 5.0.6 on 2024-06-03 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_category_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
