# Generated by Django 5.0.6 on 2024-09-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_remove_product_favorited_by_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_products',
            field=models.ManyToManyField(blank=True, help_text='Products favorited by the user.', related_name='favorite', to='store.product', verbose_name='favorite products'),
        ),
    ]
