# Generated by Django 5.0.6 on 2024-10-02 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_remove_product_likes_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
