# Generated by Django 5.0.6 on 2024-10-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='save_for_next_order',
            field=models.BooleanField(default=False),
        ),
    ]
