# Generated by Django 5.0.6 on 2024-11-21 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cart',
        ),
    ]
