# Generated by Django 5.0.6 on 2024-11-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_product_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='old_cart',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
